# Initialisation
autoload -U colors && colors
PS1="%B%{$fg[white]%}[%{$fg[white]%}%n%{$fg[white]%}@%{$fg[white]%}%M %{$fg[cyan]%}%~%{$fg[white]%}]%{$reset_color%}$%b "

# Options
setopt share_history
setopt append_history
setopt autocd

# History
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.histfile

# Aliases
alias ls="ls --color=auto"
alias clear="printf '\33c\e[3J'"
alias cp="sudo cp -iv"
alias mv="sudo mv -iv"
alias mkdir="mkdir -pv"
alias copy="pbcopy <"
alias diff="vimdiff"
alias delete="trash -v -F"
alias showtrash="trash -l"
alias cleantrash="trash -s"
alias install="brew install"
alias remove="brew uninstall"
alias update="brew update;brew upgrade;brew install --cask $(brew list --cask | tr '\n' ' ');sudo softwareupdate -i -a"
alias clean="brew autoremove;brew cleanup;brew doctor"
alias search="brew search"
alias list="brew leaves;brew list --cask"
alias gitall="git pull && git add . && git commit -m 'Changes made' && git push origin main"
alias study="sudo bash /usr/local/bin/timer.sh"
alias showstudy="sudo nvim ~/.StudyLog"

# Environment Variables
export EDITOR="nvim"
export VISUAL="nvim"

# Tab Autocomplete
autoload -U compinit
zstyle ":completion:*" menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Vim Bindings
bindkey -v
export KEYTIMEOUT=1

# Cursor Shape for Different Vim Modes 
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne "\e[1 q";;      # Block
        viins|main) echo -ne "\e[5 q";; # Beam
    esac
}

zle -N zle-keymap-select
zle-line-init() {
    zle -K viins                 # Initiate `vi insert` as Keymap (Can Be Removed if `bindkey -V` Has Been Set Elsewhere)
    echo -ne "\e[5 q"
}

zle -N zle-line-init
echo -ne "\e[5 q"                # Beam Shape Cursor on Startup
preexec() { echo -ne "\e[5 q" ;  # Beam Shape Cursor for Each New Prompt
}

# LF to Switch Directories (ctrl+o)
lfcd () {
    tmp="$(mktemp -uq)"
    trap "rm -f $tmp >/dev/null 2>&1 && trap - HUP INT QUIT TERM PWR EXIT" HUP INT QUIT TERM PWR EXIT
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}

# Key Bindings
bindkey -s "^o" "^ulfcd\n"
bindkey "^[[3~" delete-char
bindkey "^[[1;3D" backward-word
bindkey "^[[1;3C" forward-word
bindkey "^A" beginning-of-line
bindkey "^L" end-of-line

# Edit Current Command in Text Editor (ctrl+e)
autoload edit-command-line; zle -N edit-command-line
bindkey "^e" edit-command-line
bindkey -M vicmd "^e" edit-command-line
bindkey -M visual "^[[3~" vi-delete
bindkey -M vicmd "^[[3~" vi-delete-char

# Plugins
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
